title: patrick.pizza
email: your-email@example.com
email: "pizza@patricksanders.net"
author: Patrick Sanders
description: >-
  The website of Patrick Sanders. 🍕
url: "https://patrick.pizza"
twitter_username: patricksanders
github_username:  patricksanders
keybase_username: patricksanders
linkedin_username: psanders7

# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
# remote_theme: poole/hyde
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
